// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BoardCell: typeof import('./components/atoms/BoardCell.vue')['default']
    Pawn: typeof import('./components/atoms/Pawn.vue')['default']
    PawnsSpot: typeof import('./components/organisms/PawnsSpot.vue')['default']
    Piramid: typeof import('./components/atoms/Pyramid.vue')['default']
    Pyramid: typeof import('./components/atoms/Pyramid.vue')['default']
    SpotCell: typeof import('./components/atoms/SpotCell.vue')['default']
  }
}

export { }
